deploy_test:
  image: node:latest
  stage: test
  environment: 
    name: test
    url: https://test.jordonleach.dev
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy --only hosting:test -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

deploy_prod:
  when: manual
  image: node:latest
  stage: deploy
  environment:
    name: production
    url: https://jordonleach.dev
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy --only hosting:production -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

